### ISSUE TITLE
Timesave improvement

### ISSUE THREAD

**Issue by stylesuxx** [PirateBox-Dev/arch_rpi_image_prepare#10]
Timesave may be improved by simply touching the right file on ARCH. This will obsolete the writing of a file, still this might not be as simple to realize in combination with the SD improvements.

**Comment by MaStr** [comment]
This can be a global feature, can't it?

**Comment by MaStr** [comment]
Done with 18be32c8c9ac3b6208a08f9bb64217e4d68e32b0 and further commits on PirateBoxScripts
