### ISSUE TITLE
Unziped filename

### ISSUE THREAD

**Issue by MaStr** [PirateBox-Dev/arch_rpi_image_prepare#6]
It would be more comfortable for Windows users, if the unzipped filename has the suffix .img , whith that filename, the SD Card image writing software detects the image file.

piratebox_rpi.img , maybe?

**Comment by stylesuxx** [comment]
Hmmm, it should have the suffix *.img, take a look here => https://github.com/PirateBox-Dev/arch_rpi_image_prepare/blob/feature/test-checklist/Makefile#L21

**Comment by stylesuxx** [comment]
OK, the Makefile now spits out the zipped image, either piratebox-rpi.zip or piratebox-rpi2.zip depending on the ARCH parameter.
I think I should add some kind of version number. Is it enough to add the RPi image version (*piratebox-rpi(2)_x.y.z.img.zip*), or do you want to have the PirateBox version also in the filename (*piratebox_x_y_z-rpi(2)_x.y.z.img.zip*)?

**Comment by MaStr** [comment]
The filename should be:

  ${sources}_${version}-${buildnum}.img.zip

${sources} = PirateBox / LibraryBox   (We plan to bring bother closer together)
${version} = ${sources} - Release version. Like the next PirateBox release 1.0.7
${buildnum} = Number of Build for RPi/other , used for inter sourceversion rebuilds, like forgetting to ship one package dependency.

so the result would be for PirateBox
piratebox_1.0.7-1.img.zip

What do you think?

**Comment by stylesuxx** [comment]
That is OK with me, we need to put the RPi Version in there too, so maybe

${sources}_(rpi|rpi2)_${version}-${buildnum}.img.zip

**Comment by MaStr** [comment]
Yes, I forgot about the ${arch} or ${boardname}

**Comment by stylesuxx** [comment]
Alright I will adapt it to
```
${sources}_${arch}_${version}-${buildnum}.img.zip
```

Where all needed parameters may be passed as build var, just like *arch*, and default to the following:
```
piratebox_rpi_x.y.z-0.img.zip
```

So the pre release images will be:
* piratebox_rpi_1.0.7-0.img.zip
* piratebox_rpi2_1.0.7-0.img.zip

and the first "downloadable" release will be:
* piratebox_rpi_1.0.7-1.img.zip
* piratebox_rpi2_1.0.7-1.img.zip

**Comment by MaStr** [comment]
:+1:

**Comment by MaStr** [comment]
Maybe you pull the direct version from http://downloads.piratebox.de/ or pull the version tag, build and push the correct version to the build? Just to be consistent. Well, would be interesting with a pre-release testing build.

What about adding a build-date when pushing a 0 release?

Just brainstorming...

**Comment by stylesuxx** [comment]
Build date is an interesting idea, maybe we should have build date instead of release Nr?

About pulling the version, yes I was thinking about something like this yesterday and even added it to my TODO list.
